# Site settings
author: Randall Williams
title: The Developers Advocate 
header-img: img/home-bg.png
email: randallw1996@gmail.com
copyright_name: Randall Williams
description: > # this means to ignore newlines until "baseurl:"
  An aspiring Software Engineers journey to learn code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Vito60

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
